export interface Metric {
  k: string;
  label: string;
  sub: string;
}

export interface CountryMetrics {
  cost: number;
  housing: number;
  groceries: number;
  healthcare: number;
  education: number;
  safety: number;
  weather: number;
  language: number;
  family: number;
  visa: number;
  nightlife: number;
  nature: number;
  culture: number;
  shopping: number;
  transport: number;
  internet: number;
  politics: number;
  expat: number;
}

export interface Country {
  id: string;
  flag: string;
  flagEmoji: string;
  name: string;
  eu: boolean;
  visa: string;
  you: number;
  partner: number;
  metrics: CountryMetrics;
  keyPoints: {
    pros: string[];
    cons: string[];
    thingsToDo: string[];
    watchOut: string[];
  };
}

export const ALL_METRICS: Metric[] = [
  { k: "cost", label: "Cost of living", sub: "Day-to-day affordability" },
  {
    k: "housing",
    label: "Housing affordability",
    sub: "Property and rental costs",
  },
  {
    k: "groceries",
    label: "Groceries & food quality",
    sub: "Supermarket cost and quality",
  },
  { k: "healthcare", label: "Healthcare quality", sub: "Public health system" },
  {
    k: "education",
    label: "Education quality",
    sub: "Schools and PISA scores",
  },
  { k: "safety", label: "Safety & crime", sub: "Crime rates and stability" },
  {
    k: "weather",
    label: "Weather & climate",
    sub: "Sun, seasons, liveability",
  },
  {
    k: "language",
    label: "Language accessibility",
    sub: "English or easy integration",
  },
  {
    k: "family",
    label: "Family friendly",
    sub: "Childcare, schools, family culture",
  },
  { k: "visa", label: "Visa ease", sub: "Digital nomad visa, residency" },
  {
    k: "nightlife",
    label: "Nightlife & entertainment",
    sub: "Bars, restaurants, culture",
  },
  {
    k: "nature",
    label: "Nature & outdoors",
    sub: "Beaches, mountains, hiking",
  },
  {
    k: "culture",
    label: "Culture & history",
    sub: "Museums, architecture, heritage",
  },
  {
    k: "shopping",
    label: "Shopping & amenities",
    sub: "Retail, markets, services",
  },
  {
    k: "transport",
    label: "Transport & connectivity",
    sub: "Trains, flights, public transit",
  },
  {
    k: "internet",
    label: "Internet & infrastructure",
    sub: "Broadband speed, reliability",
  },
  {
    k: "politics",
    label: "Political stability",
    sub: "Democracy, freedoms, rights",
  },
  { k: "expat", label: "Expat community", sub: "English-speaking network" },
];

export const COUNTRIES: Country[] = [
  {
    id: "spain",
    flag: "ES",
    flagEmoji: "🇪🇸",
    name: "Spain",
    eu: true,
    visa: "Digital Nomad Visa — up to 5 years, renewable",
    you: 4.5,
    partner: 4,
    metrics: {
      cost: 7.5,
      housing: 7.5,
      groceries: 7.5,
      healthcare: 9.2,
      education: 8.0,
      safety: 9.0,
      weather: 8.5,
      language: 6.0,
      family: 9.0,
      visa: 8.5,
      nightlife: 7.5,
      nature: 8.5,
      culture: 8.0,
      shopping: 7.0,
      transport: 7.5,
      internet: 7.0,
      politics: 6.5,
      expat: 8.5,
    },
    keyPoints: {
      pros: ["Great weather", "Beach lifestyle", "Family friendly"],
      cons: ["Bureaucracy", "Job market tough"],
      thingsToDo: ["Beach cities", "Pyrenees skiing"],
      watchOut: ["Learn Spanish for jobs"],
    },
  },
  {
    id: "portugal",
    flag: "PT",
    flagEmoji: "🇵🇹",
    name: "Portugal",
    eu: true,
    visa: "D7 Visa — passive income, renewable",
    you: 4.5,
    partner: 4.5,
    metrics: {
      cost: 7.5,
      housing: 7.0,
      groceries: 7.5,
      healthcare: 8.5,
      education: 8.0,
      safety: 9.5,
      weather: 8.5,
      language: 7.5,
      family: 8.5,
      visa: 9.0,
      nightlife: 7.5,
      nature: 8.0,
      culture: 8.5,
      shopping: 7.0,
      transport: 8.0,
      internet: 7.5,
      politics: 7.5,
      expat: 9.0,
    },
    keyPoints: {
      pros: ["Safe", "Good weather", "D7 visa is straightforward"],
      cons: ["Housing crunch in Lisbon"],
      thingsToDo: ["Lisbon culture", "Algarve beaches"],
      watchOut: ["Lisbon housing shortage"],
    },
  },
  {
    id: "croatia",
    flag: "HR",
    flagEmoji: "🇭🇷",
    name: "Croatia",
    eu: true,
    visa: "EU residence — digital nomad 2yr",
    you: 4,
    partner: 4,
    metrics: {
      cost: 7.5,
      housing: 7.5,
      groceries: 7.5,
      healthcare: 7.5,
      education: 7.5,
      safety: 9.0,
      weather: 7.5,
      language: 3.5,
      family: 7.5,
      visa: 8.5,
      nightlife: 7.0,
      nature: 9.0,
      culture: 8.0,
      shopping: 6.5,
      transport: 7.0,
      internet: 6.5,
      politics: 6.5,
      expat: 6.5,
    },
    keyPoints: {
      pros: ["Coastline", "Weather", "More affordable"],
      cons: ["Language", "Economy"],
      thingsToDo: ["Island hopping", "Dubrovnik"],
      watchOut: ["Croatian needed for jobs"],
    },
  },
  {
    id: "estonia",
    flag: "EE",
    flagEmoji: "🇪🇪",
    name: "Estonia",
    eu: true,
    visa: "e-Residency — digital nation, no visa needed for EU",
    you: 4,
    partner: 4,
    metrics: {
      cost: 7.0,
      housing: 7.0,
      groceries: 7.0,
      healthcare: 8.0,
      education: 8.5,
      safety: 9.5,
      weather: 4.0,
      language: 7.5,
      family: 7.0,
      visa: 10,
      nightlife: 6.0,
      nature: 6.5,
      culture: 6.5,
      shopping: 6.5,
      transport: 7.5,
      internet: 9.0,
      politics: 8.5,
      expat: 7.5,
    },
    keyPoints: {
      pros: ["Digital nomad friendly", "e-Residency", "Great internet"],
      cons: ["Dark winters", "Small"],
      thingsToDo: ["Tallinn old town", "Lahemaa parks"],
      watchOut: ["Very dark winters"],
    },
  },
  {
    id: "germany",
    flag: "DE",
    flagEmoji: "🇩🇪",
    name: "Germany",
    eu: true,
    visa: "EU Blue Card — skilled worker",
    you: 4.5,
    partner: 4.5,
    metrics: {
      cost: 6.0,
      housing: 6.0,
      groceries: 6.5,
      healthcare: 9.0,
      education: 9.0,
      safety: 9.0,
      weather: 5.0,
      language: 4.5,
      family: 8.5,
      visa: 7.0,
      nightlife: 7.5,
      nature: 7.5,
      culture: 9.5,
      shopping: 7.0,
      transport: 9.0,
      internet: 7.5,
      politics: 8.0,
      expat: 8.0,
    },
    keyPoints: {
      pros: ["Economy", "Healthcare", "Central EU"],
      cons: ["Language required", "Bureaucracy"],
      thingsToDo: ["Berlin culture", "Bavaria Alps"],
      watchOut: ["German essential for jobs"],
    },
  },
  {
    id: "ireland",
    flag: "IE",
    flagEmoji: "🇮🇪",
    name: "Ireland",
    eu: true,
    visa: "Critical Skills — employment based",
    you: 4,
    partner: 3.5,
    metrics: {
      cost: 5.0,
      housing: 4.5,
      groceries: 6.0,
      healthcare: 7.5,
      education: 8.0,
      safety: 9.0,
      weather: 4.5,
      language: 9.5,
      family: 7.5,
      visa: 6.5,
      nightlife: 7.5,
      nature: 7.5,
      culture: 7.0,
      shopping: 6.5,
      transport: 7.5,
      internet: 7.0,
      politics: 7.5,
      expat: 8.5,
    },
    keyPoints: {
      pros: ["English", "Tech jobs", "EU member"],
      cons: ["Housing crisis", "Expensive"],
      thingsToDo: ["Dublin", "West coast"],
      watchOut: ["Dublin housing impossible"],
    },
  },
  {
    id: "england",
    flag: "GB",
    flagEmoji: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    name: "England",
    eu: false,
    visa: "No visa for him (home) — Belarusian: FLR partner route",
    you: 4,
    partner: 3.5,
    metrics: {
      cost: 4.5,
      housing: 4.0,
      groceries: 5.5,
      healthcare: 6.5,
      education: 7.5,
      safety: 7.0,
      weather: 4.5,
      language: 10,
      family: 7.0,
      visa: 3.5,
      nightlife: 8.5,
      nature: 7.0,
      culture: 9.5,
      shopping: 8.0,
      transport: 9.0,
      internet: 7.5,
      politics: 6.0,
      expat: 7.5,
    },
    keyPoints: {
      pros: ["Home", "English", "London opportunities"],
      cons: ["Cost", "Weather", "Visa complexity"],
      thingsToDo: ["London", "Lake District"],
      watchOut: ["Belarusian visa complex"],
    },
  },
  {
    id: "netherlands",
    flag: "NL",
    flagEmoji: "🇳🇱",
    name: "Netherlands",
    eu: true,
    visa: "Knowledge Migrant Visa — highly skilled",
    you: 4.5,
    partner: 4.5,
    metrics: {
      cost: 5.5,
      housing: 4.5,
      groceries: 6.0,
      healthcare: 8.5,
      education: 9.0,
      safety: 8.5,
      weather: 5.0,
      language: 9.5,
      family: 8.5,
      visa: 9.0,
      nightlife: 8.0,
      nature: 7.0,
      culture: 9.0,
      shopping: 7.5,
      transport: 9.5,
      internet: 8.5,
      politics: 7.5,
      expat: 9.5,
    },
    keyPoints: {
      pros: [
        "Excellent English",
        "High quality of life",
        "Great work-life balance",
      ],
      cons: ["Housing crisis", "Rainy weather"],
      thingsToDo: ["Cycling everywhere", "Canal cities"],
      watchOut: ["Housing shortage severe"],
    },
  },
  {
    id: "poland",
    flag: "PL",
    flagEmoji: "🇵🇱",
    name: "Poland",
    eu: true,
    visa: "EU Right of Residence — no visa needed",
    you: 4,
    partner: 4,
    metrics: {
      cost: 8.5,
      housing: 8.0,
      groceries: 8.0,
      healthcare: 7.5,
      education: 8.0,
      safety: 8.5,
      weather: 5.0,
      language: 3.5,
      family: 7.5,
      visa: 10,
      nightlife: 7.0,
      nature: 7.5,
      culture: 8.5,
      shopping: 8.0,
      transport: 7.5,
      internet: 7.5,
      politics: 6.0,
      expat: 7.0,
    },
    keyPoints: {
      pros: ["Affordable", "EU member", "Growing tech scene"],
      cons: ["Language barrier"],
      thingsToDo: ["Krakow old town", "Tatra mountains"],
      watchOut: ["Learn Polish for deeper integration"],
    },
  },
  {
    id: "sweden",
    flag: "SE",
    flagEmoji: "🇸🇪",
    name: "Sweden",
    eu: true,
    visa: "Personnummer — EU registration",
    you: 4,
    partner: 4,
    metrics: {
      cost: 4.0,
      housing: 5.0,
      groceries: 6.0,
      healthcare: 9.0,
      education: 9.5,
      safety: 9.0,
      weather: 3.5,
      language: 8.5,
      family: 8.0,
      visa: 10,
      nightlife: 7.0,
      nature: 8.5,
      culture: 8.0,
      shopping: 6.0,
      transport: 8.0,
      internet: 8.0,
      politics: 8.5,
      expat: 7.5,
    },
    keyPoints: {
      pros: [
        "High quality of life",
        "Excellent social services",
        "Stunning nature",
      ],
      cons: ["Dark winters", "Expensive"],
      thingsToDo: ["Archipelago", "Northern lights"],
      watchOut: ["Short daylight in winter"],
    },
  },
  {
    id: "austria",
    flag: "AT",
    flagEmoji: "🇦🇹",
    name: "Austria",
    eu: true,
    visa: "EU Red-White-Red Card — key employee",
    you: 4.5,
    partner: 4.5,
    metrics: {
      cost: 5.5,
      housing: 5.5,
      groceries: 6.5,
      healthcare: 9.0,
      education: 8.5,
      safety: 9.5,
      weather: 5.5,
      language: 5.5,
      family: 8.5,
      visa: 7.5,
      nightlife: 6.5,
      nature: 9.0,
      culture: 9.5,
      shopping: 6.5,
      transport: 8.5,
      internet: 7.5,
      politics: 8.0,
      expat: 7.0,
    },
    keyPoints: {
      pros: ["Beautiful Alps", "Safe", "Central EU location"],
      cons: ["German required"],
      thingsToDo: ["Skiing", "Vienna classical music"],
      watchOut: ["German essential for jobs"],
    },
  },
  {
    id: "denmark",
    flag: "DK",
    flagEmoji: "🇩🇰",
    name: "Denmark",
    eu: true,
    visa: "EU Registration — sufficient funds",
    you: 4.5,
    partner: 4.5,
    metrics: {
      cost: 4.5,
      housing: 5.0,
      groceries: 5.5,
      healthcare: 9.5,
      education: 9.5,
      safety: 9.5,
      weather: 4.5,
      language: 8.0,
      family: 9.0,
      visa: 9.0,
      nightlife: 7.5,
      nature: 7.0,
      culture: 8.0,
      shopping: 6.5,
      transport: 9.0,
      internet: 8.5,
      politics: 9.0,
      expat: 8.5,
    },
    keyPoints: {
      pros: ["Happy people", "Excellent healthcare", "Work-life balance"],
      cons: ["Expensive", "Hard to make friends"],
      thingsToDo: ["Cycling", "Copenhagen design"],
      watchOut: ["High tax on everything"],
    },
  },
  {
    id: "finland",
    flag: "FI",
    flagEmoji: "🇫🇮",
    name: "Finland",
    eu: true,
    visa: "EU Residence — no permit for EU citizen family",
    you: 4,
    partner: 4,
    metrics: {
      cost: 5.0,
      housing: 5.5,
      groceries: 6.0,
      healthcare: 9.5,
      education: 9.5,
      safety: 9.5,
      weather: 3.0,
      language: 6.5,
      family: 8.0,
      visa: 10,
      nightlife: 5.5,
      nature: 9.0,
      culture: 7.5,
      shopping: 6.0,
      transport: 7.5,
      internet: 8.0,
      politics: 9.0,
      expat: 6.5,
    },
    keyPoints: {
      pros: ["Best education", "Safest country", "Sauna culture"],
      cons: ["Dark winters", "Expensive"],
      thingsToDo: ["Northern lights", "Lakes in summer"],
      watchOut: ["Very dark winters"],
    },
  },
  {
    id: "france",
    flag: "FR",
    flagEmoji: "🇫🇷",
    name: "France",
    eu: true,
    visa: "Talent Passport — qualified professional",
    you: 4,
    partner: 4.5,
    metrics: {
      cost: 5.5,
      housing: 5.5,
      groceries: 6.0,
      healthcare: 9.0,
      education: 8.5,
      safety: 8.5,
      weather: 6.0,
      language: 4.0,
      family: 8.5,
      visa: 7.5,
      nightlife: 8.0,
      nature: 8.0,
      culture: 10,
      shopping: 7.5,
      transport: 8.5,
      internet: 7.0,
      politics: 6.5,
      expat: 7.5,
    },
    keyPoints: {
      pros: ["Culture", "Healthcare", "Geography diversity"],
      cons: ["Language barrier", "Bureaucracy"],
      thingsToDo: ["Paris museums", "Provence"],
      watchOut: ["French essential for integration"],
    },
  },
  {
    id: "italy",
    flag: "IT",
    flagEmoji: "🇮🇹",
    name: "Italy",
    eu: true,
    visa: "EU long-term resident or self-employment",
    you: 4.5,
    partner: 4.5,
    metrics: {
      cost: 6.5,
      housing: 6.0,
      groceries: 7.0,
      healthcare: 8.0,
      education: 7.5,
      safety: 8.5,
      weather: 7.0,
      language: 3.5,
      family: 8.5,
      visa: 7.0,
      nightlife: 8.0,
      nature: 8.5,
      culture: 10,
      shopping: 7.5,
      transport: 7.5,
      internet: 6.5,
      politics: 5.5,
      expat: 7.0,
    },
    keyPoints: {
      pros: ["Culture", "Food", "Weather"],
      cons: ["Bureaucracy", "Unemployment"],
      thingsToDo: ["Art cities", "Amalfi coast"],
      watchOut: ["Learn Italian for jobs"],
    },
  },
  {
    id: "belgium",
    flag: "BE",
    flagEmoji: "🇧🇪",
    name: "Belgium",
    eu: true,
    visa: "EU Work Permit — most EU jobs don't need one",
    you: 4,
    partner: 4,
    metrics: {
      cost: 5.5,
      housing: 5.5,
      groceries: 6.0,
      healthcare: 8.5,
      education: 8.5,
      safety: 8.0,
      weather: 5.0,
      language: 7.0,
      family: 8.0,
      visa: 9.0,
      nightlife: 7.5,
      nature: 6.5,
      culture: 8.0,
      shopping: 7.0,
      transport: 9.0,
      internet: 7.5,
      politics: 7.0,
      expat: 8.5,
    },
    keyPoints: {
      pros: ["EU Capital", "Central location", "Good schools"],
      cons: ["Weather", "Bureaucracy"],
      thingsToDo: ["Brussels EU", "Bruges"],
      watchOut: ["Trilingual (NL/FR/DE)"],
    },
  },
  {
    id: "greece",
    flag: "GR",
    flagEmoji: "🇬🇷",
    name: "Greece",
    eu: true,
    visa: "EU Long-Term Resident — 5 years",
    you: 4,
    partner: 4.5,
    metrics: {
      cost: 7.5,
      housing: 7.0,
      groceries: 7.5,
      healthcare: 7.0,
      education: 7.5,
      safety: 8.5,
      weather: 8.0,
      language: 2.5,
      family: 8.0,
      visa: 7.5,
      nightlife: 7.5,
      nature: 9.0,
      culture: 9.5,
      shopping: 6.5,
      transport: 6.5,
      internet: 6.0,
      politics: 5.0,
      expat: 6.5,
    },
    keyPoints: {
      pros: ["Weather", "Sea", "Affordable"],
      cons: ["Economy", "Language"],
      thingsToDo: ["Islands", "Ancient sites"],
      watchOut: ["Economy still recovering"],
    },
  },
  {
    id: "czechia",
    flag: "CZ",
    flagEmoji: "🇨🇿",
    name: "Czechia",
    eu: true,
    visa: "Employee Card — blue card EU",
    you: 4,
    partner: 4,
    metrics: {
      cost: 7.5,
      housing: 7.0,
      groceries: 7.5,
      healthcare: 8.0,
      education: 8.0,
      safety: 9.0,
      weather: 4.5,
      language: 3.0,
      family: 7.5,
      visa: 8.0,
      nightlife: 7.5,
      nature: 7.0,
      culture: 8.5,
      shopping: 7.5,
      transport: 8.0,
      internet: 7.5,
      politics: 6.5,
      expat: 7.5,
    },
    keyPoints: {
      pros: ["Affordable", "Safe", "Central Europe"],
      cons: ["Language barrier"],
      thingsToDo: ["Prague Christmas markets", "Czech Switzerland"],
      watchOut: ["Czech essential"],
    },
  },
  {
    id: "hungary",
    flag: "HU",
    flagEmoji: "🇭🇺",
    name: "Hungary",
    eu: true,
    visa: "EU Residence — employment based",
    you: 3.5,
    partner: 3.5,
    metrics: {
      cost: 8.5,
      housing: 8.0,
      groceries: 8.0,
      healthcare: 7.0,
      education: 7.0,
      safety: 8.0,
      weather: 5.0,
      language: 2.5,
      family: 6.5,
      visa: 8.5,
      nightlife: 7.0,
      nature: 6.5,
      culture: 7.5,
      shopping: 8.0,
      transport: 7.0,
      internet: 6.5,
      politics: 4.0,
      expat: 5.5,
    },
    keyPoints: {
      pros: ["Affordable", "Thermal baths"],
      cons: ["Politics", "Language"],
      thingsToDo: ["Budapest spas", "Lake Balaton"],
      watchOut: ["Political concerns"],
    },
  },
  {
    id: "romania",
    flag: "RO",
    flagEmoji: "🇷🇴",
    name: "Romania",
    eu: true,
    visa: "EU Right — no permit needed",
    you: 3.5,
    partner: 3.5,
    metrics: {
      cost: 9.0,
      housing: 8.5,
      groceries: 8.5,
      healthcare: 6.5,
      education: 6.5,
      safety: 8.0,
      weather: 5.5,
      language: 2.0,
      family: 6.5,
      visa: 9.5,
      nightlife: 6.5,
      nature: 7.0,
      culture: 7.0,
      shopping: 8.0,
      transport: 6.0,
      internet: 6.0,
      politics: 4.5,
      expat: 5.0,
    },
    keyPoints: {
      pros: ["Very affordable", "EU member"],
      cons: ["Healthcare", "Infrastructure"],
      thingsToDo: ["Carpathians", "Bucharest"],
      watchOut: ["Medical tourism for procedures"],
    },
  },
  {
    id: "bulgaria",
    flag: "BG",
    flagEmoji: "🇧🇬",
    name: "Bulgaria",
    eu: true,
    visa: "EU Long-Term Resident — 5 years",
    you: 3.5,
    partner: 3.5,
    metrics: {
      cost: 9.0,
      housing: 8.5,
      groceries: 8.5,
      healthcare: 6.0,
      education: 6.0,
      safety: 7.5,
      weather: 6.0,
      language: 1.5,
      family: 6.0,
      visa: 8.5,
      nightlife: 6.0,
      nature: 7.0,
      culture: 7.0,
      shopping: 8.0,
      transport: 5.5,
      internet: 5.5,
      politics: 4.0,
      expat: 4.5,
    },
    keyPoints: {
      pros: ["Very affordable", "Black Sea coast"],
      cons: ["Corruption", "Language"],
      thingsToDo: ["Sunny Beach", "Sofia mountains"],
      watchOut: ["Low wages"],
    },
  },
  {
    id: "slovakia",
    flag: "SK",
    flagEmoji: "🇸🇰",
    name: "Slovakia",
    eu: true,
    visa: "EU Blue Card",
    you: 3.5,
    partner: 3.5,
    metrics: {
      cost: 8.0,
      housing: 7.5,
      groceries: 8.0,
      healthcare: 7.5,
      education: 7.5,
      safety: 8.5,
      weather: 4.5,
      language: 2.5,
      family: 7.0,
      visa: 8.5,
      nightlife: 6.0,
      nature: 7.5,
      culture: 7.0,
      shopping: 7.5,
      transport: 7.0,
      internet: 6.5,
      politics: 5.5,
      expat: 5.5,
    },
    keyPoints: {
      pros: ["Affordable", "Mountains", "Tatra mountains"],
      cons: ["Language"],
      thingsToDo: ["High Tatras skiing", "Bratislava"],
      watchOut: ["Limited english"],
    },
  },
  {
    id: "slovenia",
    flag: "SI",
    flagEmoji: "🇸🇮",
    name: "Slovenia",
    eu: true,
    visa: "EU Residence — employment",
    you: 4,
    partner: 4,
    metrics: {
      cost: 7.0,
      housing: 6.5,
      groceries: 7.0,
      healthcare: 8.0,
      education: 8.0,
      safety: 9.0,
      weather: 5.5,
      language: 3.0,
      family: 7.5,
      visa: 8.5,
      nightlife: 6.5,
      nature: 9.0,
      culture: 7.5,
      shopping: 7.0,
      transport: 7.5,
      internet: 7.0,
      politics: 6.5,
      expat: 6.0,
    },
    keyPoints: {
      pros: ["Nature", "Safety", "Alps and coast"],
      cons: ["Small market"],
      thingsToDo: ["Lake Bled", "Ljubljana"],
      watchOut: ["Limited job market"],
    },
  },
  {
    id: "latvia",
    flag: "LV",
    flagEmoji: "🇱🇻",
    name: "Latvia",
    eu: true,
    visa: "EU Blue Card",
    you: 3,
    partner: 3,
    metrics: {
      cost: 8.5,
      housing: 8.0,
      groceries: 8.0,
      healthcare: 6.5,
      education: 6.5,
      safety: 8.0,
      weather: 3.5,
      language: 2.0,
      family: 6.0,
      visa: 8.5,
      nightlife: 5.5,
      nature: 6.5,
      culture: 6.5,
      shopping: 7.5,
      transport: 6.5,
      internet: 6.0,
      politics: 4.5,
      expat: 5.0,
    },
    keyPoints: {
      pros: ["Affordable", "Riga nice"],
      cons: ["Weather", "Language"],
      thingsToDo: ["Riga old town", "Jurmala"],
      watchOut: ["Cold winters"],
    },
  },
  {
    id: "lithuania",
    flag: "LT",
    flagEmoji: "🇱🇹",
    name: "Lithuania",
    eu: true,
    visa: "EU Blue Card",
    you: 3.5,
    partner: 3.5,
    metrics: {
      cost: 8.0,
      housing: 7.5,
      groceries: 8.0,
      healthcare: 7.0,
      education: 7.0,
      safety: 8.5,
      weather: 4.0,
      language: 2.0,
      family: 6.5,
      visa: 8.5,
      nightlife: 6.0,
      nature: 7.0,
      culture: 7.0,
      shopping: 7.5,
      transport: 6.5,
      internet: 6.5,
      politics: 5.5,
      expat: 5.5,
    },
    keyPoints: {
      pros: ["Affordable", "Growing tech"],
      cons: ["Weather", "Language"],
      thingsToDo: ["Vilnius old town", "Curonian spit"],
      watchOut: ["Cold winters"],
    },
  },
  {
    id: "luxembourg",
    flag: "LU",
    flagEmoji: "🇱🇺",
    name: "Luxembourg",
    eu: true,
    visa: "EU Key Employee — high salary threshold",
    you: 4.5,
    partner: 4.5,
    metrics: {
      cost: 3.0,
      housing: 4.0,
      groceries: 5.0,
      healthcare: 9.0,
      education: 9.0,
      safety: 9.5,
      weather: 5.0,
      language: 7.5,
      family: 8.5,
      visa: 6.5,
      nightlife: 6.0,
      nature: 7.5,
      culture: 7.5,
      shopping: 7.0,
      transport: 8.5,
      internet: 8.0,
      politics: 8.0,
      expat: 8.5,
    },
    keyPoints: {
      pros: ["High salaries", "Tax haven", "Safe"],
      cons: ["Housing", "Cost"],
      thingsToDo: ["Bock caves", "Luxembourg city"],
      watchOut: ["Expensive housing"],
    },
  },
  {
    id: "malta",
    flag: "MT",
    flagEmoji: "🇲🇹",
    name: "Malta",
    eu: true,
    visa: "EU Long-Term Resident",
    you: 4,
    partner: 4,
    metrics: {
      cost: 6.0,
      housing: 5.5,
      groceries: 6.5,
      healthcare: 7.5,
      education: 7.5,
      safety: 9.0,
      weather: 8.5,
      language: 7.0,
      family: 7.5,
      visa: 7.0,
      nightlife: 8.0,
      nature: 8.0,
      culture: 7.5,
      shopping: 6.5,
      transport: 6.5,
      internet: 6.5,
      politics: 6.0,
      expat: 7.5,
    },
    keyPoints: {
      pros: ["Weather", "English", "EU member"],
      cons: ["Small", "Services"],
      thingsToDo: ["Diving", "Mdina"],
      watchOut: ["Summer heat"],
    },
  },
  {
    id: "cyprus",
    flag: "CY",
    flagEmoji: "🇨🇾",
    name: "Cyprus",
    eu: true,
    visa: "EU Long-Term Resident",
    you: 3.5,
    partner: 4,
    metrics: {
      cost: 7.0,
      housing: 6.5,
      groceries: 6.5,
      healthcare: 7.0,
      education: 7.0,
      safety: 9.0,
      weather: 8.5,
      language: 4.5,
      family: 7.5,
      visa: 7.5,
      nightlife: 7.5,
      nature: 8.5,
      culture: 7.5,
      shopping: 6.0,
      transport: 5.5,
      internet: 5.5,
      politics: 4.5,
      expat: 6.5,
    },
    keyPoints: {
      pros: ["Weather", "Sea", "UK timezone"],
      cons: ["Limited flights", "Summer heat"],
      thingsToDo: ["Beaches", "Troodos mountains"],
      watchOut: ["Hot summers"],
    },
  },
];
